pipeline {
    agent any

    environment {
        IMAGE_NAME = "iboyx/student_list_api"
        DOCKER_CREDENTIALS_ID = "dockerhub-creds"
    }

    stages {
        stage('Cloner le repo') {
            steps {
                echo 'Clonage géré automatiquement par Jenkins (SCM).'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('student_list/simple_api') {
                    script {
                        docker.build("${IMAGE_NAME}", ".")
                    }
                }
            }
        }

        stage('Tester l\'image') {
            steps {
                script {
                    def container = docker.image("${IMAGE_NAME}").run('-d -p 5000:5000')
                    sleep 5
                    sh 'curl -u root:root http://localhost:5000/supmit/api/v1.0/get_student_ages'
                    container.stop()
                }
            }
        }

        stage('Pousser sur Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${IMAGE_NAME}
                    """
                }
            }
        }
    }
}
