version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ['http://localhost:8083']
    Access-Control-Allow-Methods: ['GET', 'DELETE', 'PUT', 'POST', 'HEAD', 'OPTIONS']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Content-Type', 'X-Requested-With']
